### PR TITLE
add Wal theme

### PR DESCRIPTION
**Pull request by acxz**
Let me know if you think I should decrease the number of photos or anything else you would like changed.

### CODE REVIEW

**Comment by dylhack** [comment]
Very interesting, I like it. @aaronraimist, do you recond this should go under a "tools" section or something of the sort?

**Comment by dylhack** [comment]
Hopefully, that doesn't discredit the fact that _it is a theme_, but I feel like a category like this could grow quickly as we look at more tools, so we should shed heavy light on this for the power users as its own category.

**Comment by aaronraimist** [comment]
I don't have a strong feeling one way or another. Either a separate category or just adding it to the list of themes are both fine with me.

**Review by dylhack — APPROVED** [review]

**Comment by aaronraimist** [comment]
Thanks! We can always split it out to a separate section as more tools become available.

**Pull request merged**
