### PR TITLE
Add Catppuccin themes

### PR DESCRIPTION
**Pull request by jordandrako**
Catppuccin is a collection of soft themes that has been ported to many applications. It was already ported to Element by @ghostx31, so I wanted to add it to this repo.

Source: https://github.com/catppuccin/element

Theme home page: https://github.com/catppuccin/catppuccin

Latte:
Catppuccin-Latte-Theme

Frappe:
Catppuccin-Frappe-Theme

Macchiato:
Catppuccin-Macchiato-Theme

Mocha:
Catppuccin-Mocha-Theme

### CODE REVIEW

**Comment by aaronraimist** [comment]
Cool! Does @ghostx31 want it to be part of this repo though?

**Comment by jordandrako** [comment]
Good question. I'll open an issue to ask for permission.

**Comment by ghostx31** [comment]
Yes please! I originally intended to upstream them here as well but life happened and I forgot. But feel free to go ahead.

**Comment by aaronraimist** [comment]
Great! Thanks for the confirmation and thanks @jordandrako for the PR.

**Comment by jordandrako** [comment]
Love when open source is this fast! Thanks everyone.

**Pull request merged**
